name: worflow main

on:
  workflow_run:
    workflows:
      - Feature to Dev CI
    types:
      - completed

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker images
        run: docker-compose pull

      - name: Start Docker services
        run: docker-compose up -d

      - name: Check Docker logs
        run: docker-compose logs

      - name: Wait for frontend to be ready
        run: |
          for i in {1..10}; do
            nc -zv localhost 3001 && echo "Frontend is ready" && exit 0
            echo "Waiting for frontend..."
            sleep 5
          done
          echo "Frontend did not start in time" && exit 1

      - name: Install packages in the e2e-tests
        working-directory: e2e-tests
        run: npm i

      - name: Install mocha globally for E2E tests
        run: npm i -g mocha

      - name: Run end-to-end tests
        working-directory: e2e-tests
        run: |
          npm test

      - name: Stop Docker services
        run: docker-compose down