name: worflow for dev

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies for Backend
        run: |
          cd backend
          npm install

      - name: Run Backend Unit Tests
        run: |
          cd backend
          npm test

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies for Frontend
        run: |
          cd frontend
          npm install

      - name: Run Frontend Unit Tests
        run: |
          cd frontend
          npm test

      - name: Merge dev into main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          branch: main
          commit-message: Merge dev into main
          title: Merge dev into main