name: Feature to Dev CI

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        working-directory: backend

      - name: Install Dependencies (Backend)
        working-directory: backend
        run: npm install

      - name: Run Unit Tests (Backend)
        working-directory: backend
        run: npm test

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        working-directory: frontend

      - name: Install Dependencies (Frontend)
        working-directory: frontend
        run: npm install

      - name: Run Unit Tests (Frontend)
        working-directory: frontend
        run: npm test

      - name: Merge Dev into Main
        uses: devops-actions/merge-branch@v2
        with:
          from_branch: dev
          target_branch: main
          github_token: ${{ secrets.PAT_TOKEN }}
